export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const ADD_POST_LIKE = 'ADD_POST_LIKE';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
